version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Lien vers le fichier d'init
      - ./backend/data.csv:/docker-entrypoint-initdb.d/data.csv  # Lien vers le fichier CSV
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  postgres_data:
